### ISSUE TITLE
is cordova truly integrated with react?

### ISSUE THREAD

**Issue by mgenev** [unimonkiez/react-cordova-boilerplate#8]
I'm trying out to integrate cordova and react, and the issue i'm running into is that, this react app is compiled beforehand and then handed to cordova. Which means using plugins like the device plugin is not possible? `device.platform` in any react component gives me undefined and breaks the build.

How am I supposed to use Cordova's power to talk to the device from my react components?

**Comment by unimonkiez** [comment]
It's not a question about react and cordova integration, it's more about cordova + web development.
When you run the app as a website (using `npm start`), it's much faster and easier to develop than building the application each time to make a change.

A way to solve this is to integrate Live reloading / Hot model replacement  to work also on the app (which is a nice feature I started working on).

Another way to solve this (and it's the way I'm doing right now on my own app) is to mock cordova's behavior.

What does it mean? let me explain with an example.
On cordova you have `device.uuid`, on the web we will get an exception (because `device` is undefined).
To mock that behavior I will create another uuid on the web and use global `__CORDOVA__`:
```javascript
function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000)
      .toString(16)
      .substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
    s4() + '-' + s4() + s4() + s4();
}
var uuid = __CORDOVA__ ? device.uuid : guid();
// And continue doing whatever we intended to do with uuid...
$.ajax('users', {id: uuid});
...
```   
As for performance and junk code, minification solves that for you.
In cordova's build `__CORDOVA__` is replaced with `true` and will change this row `var uuid = true ? device.uuid : guid();` to this `var uuid = device.uuid` and will also remove the function `guid` because it's no longer used anywhere.

This way to can maintain your web app working for easy development and showing/ testing features on different browsers on the computer while making sure it does what you intended.

**Comment by mgenev** [comment]
Thanks this approach is quite reasonable indeed!

**Comment by unimonkiez** [comment]
Sure :+1:
