### ISSUE TITLE
Simpler version

### ISSUE THREAD

**Issue by sebastialonso** [unimonkiez/react-cordova-boilerplate#9]
Hi, thanks for the boilerplate!
I was wondering since I'm recently starting with React and I'm not using Redux for the current project, how could I get a simpler boilerplate?
I'm talking specifically about all the actions, containers, etc. (Sadly AppRouter and App are entangled in there with other containers)

Also, why two entry points for webpack? I'm trying to understand why do I need both Client and Server entry points for just a Cordova app. Do I need both of them just for a simple app?

**Comment by unimonkiez** [comment]
You can strip the boilerplate a bit by yourself at anytime, it's quiet simple once you understand Webpack, though at the start I remember how much pain it was.

I did a server entry because I wanted to make sure the app also runs in the server, which also gives me the loading page (the one with the logo) before the execution of the scripts.

Multiple entry points also helped me determine which code can only run in the browser, and this is important, if you want to convert your project to react-native while only refactoring some views.

Anything else?

**Comment by sebastialonso** [comment]
Actually, thank you for the explanation. Webpack is completely inhuman at the start, I agree, so I appreciate the time to explain.

Cheers!

**Comment by unimonkiez** [comment]
@sebastialonso Sure :smile:
